#Crawl the web. You need (at least) two parameters:
	#frontier: The frontier of known URLs to crawl. You will initially populate this with your seed set of URLs and later maintain all discovered (but not yet crawled) URLs here.
	#index: The location of the local index storing the discovered documents.

class Crawler():
    def __init__(self):

        self.frontier_eng = [
            'https://uni-tuebingen.de/en/',
            'https://www.tuebingen.mpg.de/en',
            'https://www.tuebingen.de/en/',
            'https://health-nlp.com/people/carsten.html',
            'https://www.dzne.de/en/about-us/sites/tuebingen',
            'https://www.britannica.com/place/Tubingen-Germany',
            'https://tuebingenresearchcampus.com/en/tuebingen/general-information/local-infos/',
            'https://wanderlog.com/list/geoCategory/199488/where-to-eat-best-restaurants-in-tubingen',
            'https://wikitravel.org/en/T%C3%BCbingen',
            'https://velvetescape.com/things-to-do-in-tubingen/',
            'https://thespicyjourney.com/magical-things-to-do-in-tubingen-in-one-day-tuebingen-germany-travel-guide/',
            'https://www.outdooractive.com/en/places-to-eat-drink/tuebingen/eat-drink-in-tuebingen/21873363',
            'https://www.komoot.com/guide/210692/attractions-around-tuebingen',
            'https://bestplacesnthings.com/places-to-visit-tubingen-baden-wurttemberg-germany/',
            'https://www.citypopulation.de/en/germany/badenwurttemberg/t%C3%BCbingen/08416041__t%C3%BCbingen/',
            'https://www.braugasthoefe.de/en/guesthouses/gasthausbrauerei-neckarmueller/',
            'https://www.germany.travel/en/cities-culture/tuebingen.html',
            'https://www.tripadvisor.com/Tourism-g198539-Tubingen_Baden_Wurttemberg-Vacations.html',
            'https://www.hih-tuebingen.de/en/?no_cache=1',
            'https://tuebingenresearchcampus.com/',
            'https://cyber-valley.de/en',
            'https://www.bccn-tuebingen.de/',
            'https://www.tripadvisor.de/Attractions-g198539-Activities-Tubingen_Baden_Wurttemberg.html',
            'https://justinpluslauren.com/things-to-do-in-tubingen-germany/',
            'https://www.medizin.uni-tuebingen.de/en-de/das-klinikum',
            'https://www.medizin.uni-tuebingen.de/en-de/startseite',
            'https://bookinghealth.com/university-hospital-tuebingen',
            'https://www.eventbrite.de/d/germany--tübingen/parties/',
            'https://www.tripadvisor.de/Restaurants-g198539-c11-Tubingen_Baden_Wurttemberg.html',
            'https://www.11880.com/suche/china-restaurant/tuebingen',
            'https://de.restaurantguru.com/chinese-Tubingen-c20',
            'https://en.wikipedia.org/wiki/Neckar',
            'https://www.iksr.org/en/topics/rhine/sub-basins/neckar',
            'https://www.eventbrite.com/d/germany--tübingen/events/',
            'https://www.tripadvisor.com/Attractions-g198539-Activities-c49-Tubingen_Baden_Wurttemberg.html',
            'https://www.tripadvisor.com/Attractions-g198539-Activities-c57-Tubingen_Baden_Wurttemberg.html',
            'https://www.tuebingen.de/en/3328.html',
            'https://en.wikipedia.org/wiki/Tübingen',
            'https://www.accuweather.com/en/de/tübingen/72070/weather-forecast/167215',
            'https://www.timeanddate.com/weather/germany/tuebingen/ext',
            'https://www.tripadvisor.com/Attractions-g198539-Activities-c20-Tubingen_Baden_Wurttemberg.html',
            'https://www.yelp.com/search?cflt=bookstores&find_loc=Tübingen%2C+Baden-Württemberg',
            'https://allevents.in/tubingen',
            'https://globaltravelescapades.com/things-to-do-in-tubingen-germany/',
            'https://www.tripadvisor.com/Restaurants-g198539-Tubingen_Baden_Wurttemberg.html',
            'https://guide.michelin.com/en/de/baden-wurttemberg/tbingen/restaurants',
            'https://www.thefork.com/restaurants/tubingen-c561333',
            'https://www.medizin.uni-tuebingen.de/en-de/das-klinikum/einrichtungen/kliniken/zahn-mund-und-kieferheilkunde',
            'https://www.tripadvisor.com/Attractions-g198539-Activities-c61-Tubingen_Baden_Wurttemberg.html',
            'https://www.my-stuwe.de/en/refectory/',
            'https://www.my-stuwe.de/en/refectory/refectory-shedhalle/',
            'https://www.my-stuwe.de/en/refectory/refectory-morgenstelle-tuebingen/',
            'https://www.bahnhof.de/en/tuebingen-hbf'
            ]
        
        self.frontier_de = [
            'https://rp.baden-wuerttemberg.de/rpt/',
            'https://uni-tuebingen.de',
            'https://www.tuebingen-info.de/de/sehenswuerdigkeiten',
            'https://viel-unterwegs.de/reiseziele/deutschland/baden-wuerttemberg/tuebingen-sehenswuerdigkeiten/',
            'https://www.swr.de/swraktuell/baden-wuerttemberg/tuebingen/stocherkahn-rennen-in-tuebingen-100.htm',
            'https://www.tuebingen.de/palmer',
            'https://www.tuebingen-info.de/de/tuebinger-flair/die-tuebinger-altstadt',
            'https://www.unimuseum.uni-tuebingen.de/de/schloss-hohentuebingen',
            'https://de.wikipedia.org/wiki/Schloss_Hohentübingen',
            'https://www.tuebingen-info.de/attraktion/schloss-hohentuebingen-5180385e2e',
            'https://www.stiftskirche-tuebingen.de',
            'https://www.stiftskirche.de',
            'https://hoelderlinturm.de/',
            'https://www.tuebingen-info.de/attraktion/cotta-haus-f69a9620bd',
            'https://uni-tuebingen.de/einrichtungen/zentrale-einrichtungen/botanischer-garten/',
            'https://de.wikipedia.org/wiki/Neckar',
            'https://www.iksr.org/de/themen/rhein/teileinzugsgebiete/neckar',
            'https://www.reisetipps-europa.de/51_Reisefuehrer/7_Reisefuehrer_D_Neckar.html',
            'https://www.tuebingen.de',
            'https://www.rhenania-tuebingen.de/universitaetsstadt-tuebingen/',
            'https://uni-tuebingen.de/einrichtungen/personalvertretungen-beratung-beauftragte/lageplaene/karte-b-wilhelmstrasse-talkliniken/neue-aula/',
            'https://de.wikipedia.org/wiki/Neue_Aula_Tübingen',
            'https://www.tuepedia.de/wiki/Neue_Aula',
            'https://www.tuebingen-info.de/de/veranstaltungen#/event',
            'https://www.tuebingen.de/109.html',
            'https://www.unimuseum.uni-tuebingen.de/de/',
            'https://freizeitmonster.de/blog/parks-tuebingen',
            'https://uni-tuebingen.de/en/fakultaeten/philosophische-fakultaet/fachbereiche/geschichtswissenschaft/fachbereich/',
            'https://www.my-stuwe.de/mensa/',
            'https://www.tuepedia.de/wiki/Shedhalle',
            'https://www.my-stuwe.de/mensa/mensa-morgenstelle-tuebingen/',
            'https://uni-tuebingen.de/einrichtungen/personalvertretungen-beratung-beauftragte/lageplaene/karte-a-morgenstelle/',
            'https://de.wikipedia.org/wiki/Morgenstelle',
            ]

    def crawl(frontier, index):
        #TODO: Implement me
        pass
