version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user_pw"
      POSTGRES_DB: "search_engine_db"
    ports:
      - "5432:5432"

