version: '3.9'

services:
  db:
    build:
      context: ./db
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user_pw"
      POSTGRES_DB: "search_engine_db"
    ports:
      - "5432:5432"
    volumes:
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql